apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evercran
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: evercran.r-pkg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evercran
                port:
                  number: 3000
