volumes:
  packages:
  dbdata:

secrets:
  pg-password:
    external: true

services:
  evercran:
    image: "rhub/evercran"
    build:
      context: evercran
      platforms:
        - linux/amd64
    environment:
      - PG_USER=postgres
      - PG_HOST=db
      - PG_PASS_FILE=/run/secrets/pg-password
      - PORT=80
    depends_on:
      - db
    ports:
      - "80:80"
    secrets:
      - pg-password
    volumes:
      - packages:/packages
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: "rhub/evercran-db"
    build:
      context: postgres
      platforms:
        - linux/amd64
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-password
    volumes:
      - dbdata:/var/lib/postgresql
    secrets:
      - pg-password
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  shell:
    image: "rhub/evercran-db"
    build:
      context: shell
      platforms:
        - linux/amd64
    command: /root/entrypoint.sh
    environment:
      - PG_USER=postgres
      - PG_HOST=db
      - PG_PASS_FILE=/run/secrets/pg-password
    volumes:
      - packages:/packages
    secrets:
      - pg-password
    deploy:
      restart_policy:
        condition: any
